### ISSUE TITLE
Needlets in python

### ISSUE THREAD

**Issue by JohnPodczerwinski** [astro-informatics/s2let#45]
Hello, I'm interested in using py2slet to perform a needlet transform. Is that possible to do?

Thanks

**Comment by jasonmcewen** [comment]
Yes, that's possible.  If you just set directionality to 1, you will get an axisymmetric wavelet transform on the sphere, where the wavelets used are very similar to needlets.  

There is a very slight difference in the kernels used for needlets since they were developed independently but the wavelets have the same properties.  See Fig 1.a of [this paper](https://arxiv.org/pdf/1211.1680.pdf) for a comparison of the kernels, which I've reproduced below.  You'll see the black curve (our definition) and the blue dashed curve (needlets) are very similar.

<img width="336" alt="Screenshot 2022-02-16 at 15 57 38" src="https://user-images.githubusercontent.com/3181701/154304762-81ff8b60-3b7f-4ef7-a91d-ad5b9352a3f3.png">

In fact, we did even implement the needlet kernels as well in s2let at some point, although I don't think that is exposed in python.  

Apologies, the python documentation is lacking at present but that is something we hope to improve in future.

Hopefully that anwers your question so I'll close this issue but please just get in touch if you have any further questions.

**Comment by JohnPodczerwinski** [comment]
That makes sense. Thanks for the quick response jason!
